// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLEHwGuKt16Coeba9XYcIq-AF_mk4zBNA',
    appId: '1:594803265396:web:0ed3a0c61557bae0ea2621',
    messagingSenderId: '594803265396',
    projectId: 'importan-4e50e',
    authDomain: 'importan-4e50e.firebaseapp.com',
    storageBucket: 'importan-4e50e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFT3I4O2-CvS7gi-clLWSSx_tYI34eNM',
    appId: '1:594803265396:android:28ff9b23f2c27c46ea2621',
    messagingSenderId: '594803265396',
    projectId: 'importan-4e50e',
    storageBucket: 'importan-4e50e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr6WmuaLuZT29d_RMDbpeiE64kHojMDqE',
    appId: '1:594803265396:ios:b2fa13eab27ed941ea2621',
    messagingSenderId: '594803265396',
    projectId: 'importan-4e50e',
    storageBucket: 'importan-4e50e.appspot.com',
    iosBundleId: 'com.example.importanSkripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr6WmuaLuZT29d_RMDbpeiE64kHojMDqE',
    appId: '1:594803265396:ios:cad5efaa242c096aea2621',
    messagingSenderId: '594803265396',
    projectId: 'importan-4e50e',
    storageBucket: 'importan-4e50e.appspot.com',
    iosBundleId: 'com.example.importanSkripsi.RunnerTests',
  );
}
